server:
  port: 6999

spring:
  application:
    name: ABCis Spring Exam
    version: 1.0
  cloud:
    gateway:
      routes:
        - id: company-microservice
          uri: ${COMPANY_SERVICE_URL}
          predicates:
            - Path=/company-service/**

management:
  endpoint:
    health:
      show-details: "always"