server:
  port: 7003 # change the gateway env variable COMPANY_SERVICE_URL to this if this profile is active
  servlet:
    contextPath: /company-service

spring:
  application:
    name: ABCis Spring Exam UAT
    version: 1.0
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

management:
  endpoint:
    health:
      show-details: "always"
